NAME_STRING_LENGTH = 255
STRING_SHOW = 30
SLUG_LENGTH = 50
NAME_TITLE_LENGTH = 100
EMAIL_LENGTH = 254
USERNAME_LENGTH = 150
MIN_SCORE_VALUE = 1
MAX_SCORE_VALUE = 10

CONFIRMATION_CODE_ERROR = 'Некоректный код подтверждения.'
