# Generated by Django 3.2 on 2024-12-03 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_unique_username_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Некорректный код подтверждения.Значение кода длинной 10 символовсостоит из прописных латинских символов и десятичных цифр.', regex='^[A-Z\\d]{10}$')], verbose_name='Код подтверждения'),
        ),
    ]
